version: '3.5'
services:
  clustercontrol:
    image: severalnines/clustercontrol:1.7.5
    networks:
      - ccnet
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - cc-cmond:/etc/cmon.d
      - cc-datadir:/var/lib/mysql
      - cc-ssh:/root/.ssh
      - cc-cmonlib:/var/lib/cmon
      - cc-backups:/root/backups
    environment:
      CMON_PASSWORD_FILE: /run/secrets/CC_CMON_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/CC_MYSQL_ROOT_PASSWORD
    restart: always
    secrets:
      - CC_CMON_PASSWORD
      - CC_MYSQL_ROOT_PASSWORD
  pg_master:
    build: postgis/
    image: postgis:9.6-2.4
    networks:
      - ccnet
    ports:
      - 5550:5432
    volumes:
      - pg_master:/usr/local/pgsql/data
    depends_on:
      - clustercontrol
    env_file:
      - postgres.env
    secrets:
      - POSTGRES_PASS
    restart: always
  pg_slave1:
    image: postgis:9.6-2.4
    networks:
      - ccnet
    ports:
      - 5551:5432
    volumes:
      - pg_slave1:/usr/local/pgsql/data
    depends_on:
      - pg_master
    env_file:
      - postgres.env
    secrets:
      - POSTGRES_PASS
    restart: always
  pg_slave2:
    image: postgis:9.6-2.4
    networks:
      - ccnet
    ports:
      - 5552:5432
    volumes:
      - pg_slave2:/usr/local/pgsql/data
    depends_on:
      - pg_master
    env_file:
      - postgres.env
    secrets:
      - POSTGRES_PASS
    restart: always

volumes:
  cc-cmond:
  cc-datadir:
  cc-ssh:
  cc-cmonlib:
  cc-backups:
  pg_master:
  pg_slave1:
  pg_slave2:

networks:
  ccnet:
    ipam:
      driver: default
      config:
        - subnet: 172.2.0.0/24

secrets:
  CC_CMON_PASSWORD:
    external: true
  CC_MYSQL_ROOT_PASSWORD:
    external: true
  POSTGRES_PASS:
    external: true